### ISSUE TITLE
Possibility to change the alicourd icon to some colors or custom hex

### ISSUE THREAD

**Issue by Dedsd** [Aliucord/Aliucord#137] opened 2021-11-07 13:16 UTC
### What is it that you'd like to see?

As the duckduckgo app does, it would be interesting to be able to change the app icon color

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by Vendicated** [comment] 2021-11-07 13:16
Duplicate of #87

**Closed by Vendicated** 2021-11-07 13:16 UTC
Labels: enhancement
