### ISSUE TITLE
Root variant

### ISSUE THREAD

**Issue by ps1-hagrid** [Aliucord/Aliucord#196] opened 2022-01-20 10:51 UTC
### Discord Account

Hagrid#2662

### What is it that you'd like to see?

I would like Aliucord to have a root solution so it could replace the default Discord app (like YouTube Vanced). Because I would like all the Discord links to open in Aliucord and it to have icon pack/LawnIcons support.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by hairyfred** [comment] 2022-01-20 11:16
Firstly
"all the Discord links to open in Aliucord" This is already possible, its in the support pins
" to have icon pack/LawnIcons support." Most launchers allow you to manually assign an icon to an app from an icon pack
Secondly
Vanced has a root variant so it can log into google directly without microg, Aliucord doesnt really have a reason to have a rooted variant.

**Comment by Vendicated** [comment] 2022-01-20 16:55
It doesn't even need a root variant to do this since Discord is not a system app. So this is just a duplicate of #93

**Closed by Vendicated** 2022-01-20 16:55 UTC
Labels: enhancement
