### ISSUE TITLE
Not receiving any notifications on mobile

### ISSUE THREAD

**Issue by candroid-man** [Aliucord/Aliucord#286] opened 2022-12-04 01:44 UTC
### Discord Account

BigDankHank#1150

### What happens when the bug or crash occurs?

I never get notifications, like ever. I haven't gotten one in months since I installed it.

A few others on the Aliuwucord Discord server have also claimed to have this issue as well.

[Message from #support by chlxe#9119](https://discord.com/channels/811255666990907402/811261298997460992/1047826542857822208)
[Message from #support by PureFlake ❄#7423](https://discord.com/channels/811255666990907402/811261298997460992/1047356164536537158)

### What is the expected behaviour?

To get notifications when messaged or mentioned.

### How do you recreate this bug or crash?

1. Install Aliucord
2. See error

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by MaxAkito** [comment] 2022-12-19 09:02
Experiencing the same issue. Checked all phone settings and uninstalled all other discord instances, no change.

**Comment by Vendicated** [comment] 2022-12-19 19:15
It's a bug with your phone / issue in your Google account / issue on Discord's end / whatever and out of Aliucord's control

**Comment by TheGoldenSun** [comment] 2022-12-22 18:09
@candroid-man Here Candroid at least I'm nice to help you out: 

https://www.airdroid.com/parent-control/discord-notifications-not-working/#:~:text=Step%201%3A%20On%20Android%2C%20open,the%20main%20settings%20are%20enabled.

**Comment by TheGoldenSun** [comment] 2022-12-26 20:18
@RhythmLunatic You think that this type of article is just pretty common and regular and it doesn't support aliucord in general? I feel so bad that you did not even read the whole article yourself but basically assuming that it does not support anybody to fix the notifications themselves that makes you a complete arrogant being yourself, I'm trying to help out someone but you're over here assuming that it doesn't have any support as to how they should fix the notification.

![Screenshot_20221226_151539](https://user-images.githubusercontent.com/104534608/209581018-63b2de03-fbd9-4cdf-8a49-49899e97ba5a.png)
![Screenshot_20221226_151550](https://user-images.githubusercontent.com/104534608/209581020-a4ef261e-31e0-48cb-b0ce-b598f70811e7.png)
![Screenshot_20221226_151601](https://user-images.githubusercontent.com/104534608/209581021-0187fe2a-b0dc-4581-8b2f-bbf187aee54d.png)

**Comment by TheGoldenSun** [comment] 2022-12-26 20:20
@RhythmLunatic As much as I like the mod itself, this is clear that you're rude.

**Comment by TheGoldenSun** [comment] 2022-12-26 20:21
@candroid-man Anyway, my apologies Candroid, Don't mind them, just click on the website so fix the notifications.

**Comment by DiamondMiner88** [comment] 2022-12-26 20:22
The issue is aliucord specific and 3rd party generic tutorials won't help in anyway

**Comment by TheGoldenSun** [comment] 2022-12-26 20:23
Exactly, which is why it's @candroid-man should fix it themselves, what's so wrong of me helping them?

**Comment by candroid-man** [comment] 2022-12-26 20:24
I was able to resolve the issue, kind of.

I completely uninstalled Discord and Aliucord, and reinstalled Aliucord and it works sometimes. Sometimes I will get a notification 10 or 20 minutes after I should have received it, or sometimes I won't get them at all.

I believe this is an issue with Aliucord but I'm not a developer

**Comment by Juby210** [comment] 2022-12-26 20:24
because it is not possible to fix by "just enabling notifications in settings". Discord sometimes doesn't get notifications from firebase and that's all

**Comment by TheGoldenSun** [comment] 2022-12-26 20:25
> I was able to resolve the issue, kind of.
> 
> I completely uninstalled Discord and Aliucord, and reinstalled Aliucord and it works sometimes. Sometimes I will get a notification 10 or 20 minutes after I should have received it, or sometimes I won't get them at all.
> 
> I believe this is an issue with Aliucord but I'm not a developer

I'm not either, but this is easy as pie to fix it manually if no one is able to fix on GitHub, it's not that difficult.

**Comment by Juby210** [comment] 2022-12-26 20:26
@TheGoldenSun it is not possible to fix by "just enabling notifications in settings". This isn't related to Discord/Aliucord/System settings at all.

**Comment by Juby210** [comment] 2023-05-04 21:09
Closing as it is most likely impossible to fix by us, as it is out of our control.

**Closed by Juby210** 2023-05-04 21:09 UTC
Labels: wontfix
