### ISSUE TITLE
user proflie data like pronouns and about me's not displaying

### ISSUE THREAD

**Issue by zooki2006** [Aliucord/Aliucord#451] opened 2024-05-23 14:49 UTC
### Discord Account

zukigaymer

### What happens when the bug or crash occurs?

Peoples profiles don't show their pronouns or about me, although still shows status's.
![Screenshot_20240523-112041](https://github.com/Aliucord/Aliucord/assets/55743069/4c17a9b6-c6ed-403e-8288-a954e3f0f587)

### What is the expected behaviour?

I expect it to show a users pronouns/about me when viewing a profile.

### How do you recreate this bug or crash?

0. (Im on grapheneos)
1. Open aliucord
2. View a users profile

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by janisslsm** [comment] 2024-05-23 17:05
GrapheneOS issue. If i recall correctly, we looked into this before and it was due to AOT/JIT changes in graphene.

**Comment by rushiiMachine** [comment] 2024-05-23 17:40
duplicate of #427

**Closed by rushiiMachine** 2024-05-23 17:40 UTC
Labels: duplicate
