### ISSUE TITLE
Analytics still work

### ISSUE THREAD

**Issue by asakura42** [Aliucord/Aliucord#257] opened 2022-07-16 19:24 UTC
### What is it that you'd like to see?

Even after patching discord connects to crashlytics.com and adjust.com.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by ItzOnlyAnimal** [comment] 2022-07-16 19:37
you love google gms

**Comment by Vendicated** [comment] 2022-07-16 19:53
any more info? Screenshots? what endpoints specifically? how did you determine it?

**Comment by Vendicated** [comment] 2022-07-17 14:03
I have tested with a proxy and cannot reproduce requests to either of those hosts.

My system does send a request to firebase-settings.crashlytics.com as can be seen here however, this is likely play services doing and not Aliucord's as I did not even have Aliucord open at that time.
![](https://cdn.discordapp.com/attachments/811262084968742932/998226506956410910/unknown.png) 

It never connects to Adjust at all and when actually opening Aliucord, the only requests that happen are the following
![](https://cdn.discordapp.com/attachments/811262084968742932/998226776918601838/unknown.png)

Please provide more info and collect the paylods these requests send with a proxy such as Charles Proxy or Burpsuite

**Comment by DiamondMiner88** [comment] 2022-07-17 14:07
My device doesn't even connect to either crashlytics.com and adjust.com, cannot reproduce

**Comment by asakura42** [comment] 2022-07-17 14:27
@ItzOnlyAnimal
> you love google gms
I don't use google bruh

@Vendicated 
I use Tracker Control (https://github.com/TrackerControl/tracker-control-android) for tracking and blocking shit. It writes that patched Discord connects to to these websites. It works as local vpn services so any packets collected are produced with patched Discord.

**Comment by Vendicated** [comment] 2022-07-17 14:58
Please provide more info and collect the paylods these requests send with a proxy such as Charles Proxy or Burpsuite

**Comment by Vendicated** [comment] 2022-07-21 10:47
since you haven't posted any more info, not even Screenshots, there's no way for us to investigate further. Closing for now but feel free to reply with more info whenever

**Closed by Vendicated** 2022-07-21 10:47 UTC
Labels: enhancement, invalid
